Add js for add and remove lists
Tadessejemal1/To-Do-list-Web pull request #2
Opened 2022-08-11 12:12 UTC by Tadessejemal1

Create Add and remove lists

2022-08-11 22:01 UTC, Tadessejemal1 commented
When We Add the todo-list
 
![image](https://user-images.githubusercontent.com/85793292/184249880-ddf8ad33-4813-4c62-b7bb-0fd229d617ff.png)


When I clicked the checkbox the checked one line over the text
 
![image](https://user-images.githubusercontent.com/85793292/184249909-4b2a3d2b-175f-4077-b669-d73f1951ed4e.png)


When I clicked the deleted icon, the list data is removed. 

 
![image](https://user-images.githubusercontent.com/85793292/184249948-e3f31fd5-eb9b-4fda-a67c-efdcada93f57.png)


The added data are stored on the local storage.
 
![image](https://user-images.githubusercontent.com/85793292/184249984-5847c53b-1924-4826-96e7-cb490ac77e38.png)

2022-08-12 12:21 UTC, cynthiainga requested changes
Hi @Tadessejemal1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [x] No linters ✔️ 
- [x] Used the correct Github Flow 👍 
- [x] Descriptive pull request 👍 ✔️ 

## Required Changes ♻️

- [x] Please kindly check the comments under the review 👇 👇


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 12:21 UTC, cynthiainga commented on src/index.js
> +
- [ ] Please make sure to delete the comments lines of code in your file to keep a clean codebase 🙃🙃

2022-08-12 12:21 UTC, cynthiainga commented on src/index.js
> +        },
- [ ] All the tasks should have the property index set to the value of the new array length (i.e. if a 4th task is added to the list, the index of that task should equal 4) but for you, there is no property of index 🙃 🙃, please kindly fix that.

This is the look of your data in the local storage:
<img width="623" alt="Screen Shot 2022-08-12 at 13 59 31" src="https://user-images.githubusercontent.com/74501523/184351429-6e88512a-5102-4a4e-9da3-92300b942ae9.png">

- [ ] You suppose to have a property of index and not of color 😁 😁

2022-08-12 12:21 UTC, cynthiainga commented on src/index.js
> +// }
- [ ] Please make sure to delete the comments lines of code in your file to keep a clean codebase 🙃🙃

2022-08-12 12:21 UTC, cynthiainga commented on src/template.html
> +        </div> -->
- [ ] Same remarque about the comments line of code, please make sure to delete the comments lines of code in your file to keep a clean codebase 🙃🙃

2022-08-12 15:32 UTC, Tadessejemal1 commented
Ias the previous reviewers mentioned I can fix the problems by adding an id for each value. this is a screenshot.
![image](https://user-images.githubusercontent.com/85793292/184389102-fedb9eee-2430-498b-8c4b-b46a91efad61.png)

2022-08-12 15:59 UTC, Nemwel-Boniface approved these changes
## Hello @Tadessejemal1               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making all the changes requested by a previous reviewer good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] [OPTIONAL] Your project was failing to start from my end and was throwing the error ```Missing script: "start"```. On further inspection, I realized that you do not have the "start" script to enable someone to run your project from their local machines. To fix this, you simply need to add ```    "start": "webpack serve --open", ``` after "dev" and it will work perfectly.

**This is the error it throws without it:**

![image](https://user-images.githubusercontent.com/86318284/184394756-3a43dd14-69dc-4d58-9445-4cf39a74e7f2.png)

**This is the correct scripts:**

```
"scripts": {
    "build": "webpack",
    "start": "webpack serve --open",
    "dev": "webpack serve"
  },
```

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 16:31 UTC, merged